//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class RoleRelation
{
	public RoleRelation ()
	{

	}

	public int _targetID;
	private int _relationship;
	public int Relationship{
		get{return _relationship;}
		set{
			if (value > 1000)
				_relationship = 1000;
			else if (value < -1000)
				_relationship = -1000;
			else
				_relationship = value;
		}
	}

	private int _common_fans;
	public int CommonFans{
		get{return _common_fans;}
		set{
			if (value >100000000)
				_common_fans = 100000000;
			else if (value < 0)
				_common_fans = 0;
			else
				_common_fans = value;
		}
	}

	private int _base_add_rate;

	private int _change_add_rate;
	public int ChangeAddRate{
		private get{return _change_add_rate;}
		set{
			if (value > 50)
				_change_add_rate = 50;
			else if (value < -50)
				_change_add_rate = -50;
			else
				_change_add_rate = value;
		}
	}

	public int GetAddRate{
		get{return _base_add_rate + _change_add_rate;}
	}

	public int RelationshipFresh(int baseCount)
	{
		int result = (baseCount > 0) ? (ExternData.RoleRelationData1 + GetAddRate) / ExternData.RoleRelationData2 * baseCount : (ExternData.RoleRelationData1 - GetAddRate) / ExternData.RoleRelationData2 * baseCount;
		int change_count = 0;
		if (baseCount > 0)
			change_count = baseCount / 2 > 1 ? baseCount / 2 : 1;
		else
			change_count = baseCount / 2 < -1 ? baseCount / 2 : -1;
		this.ChangeAddRate += change_count;
		return result;
	}
}

