//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public enum RoleLocationEnum
{
	Singer = 1,
	Actor = 2,
	Host = 3,
	Model = 4,
	Agent = 5,
	Producer = 6,
	TVProducer = 7,
	MusicProducer = 8,
	ShopKeeper = 9,
}

