//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public static class ExternData
{
	public static int RoleRelationData1 = 60;
	public static int RoleRelationData2 = 10;
    public static double TrainingFixData = 0.8;
}

