//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Item
{
	public Item ()
	{
	}

	public int ID;
    public int number;//数量
    private bool canUse;//是否可以使用
    private bool isContinues;//是否持有即生效

    public bool CanUse
    {
        get
        {
            return canUse;
        }
    }

    public bool IsContinues
    {
        get
        {
            return isContinues;
        }
    }

    public int property1;//属性1
    public int property2;//属性2
    public int property3;//属性3
    public int property4;//属性4

    public int property1_num;//属性1数值
    public int property2_num;//属性2数值
    public int property3_num;//属性3数值
    public int property4_num;//属性4数值

}

